### ISSUE TITLE
🐛 DReps should be able to vote on all governance actions 

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2527]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Context

DReps should be able to vote all governance actions under full governance mode on protocol version 10 as in current preview testnet. Currently, Info, Treasury Withdrawals and Parameter change governance actions are allowed for DReps to vote.
<img width="680" alt="Screenshot 2024-12-16 at 12 20 33" src="https://github.com/user-attachments/assets/5227ec23-1b49-4c7e-8250-12b620660288" />

### Steps to reproduce

1. Connect GovTool as DRep
2. Visit any governance actions other than Info, Treasury Withdrawals and Parameter change governance actions.
3. No vote option as DRep

### Actual behavior

No vote option as DRep

### Expected behavior

DReps should be able to vote on all governance actions.

**Comment by MSzalowski** [comment]
Fixed within this PR:
https://github.com/IntersectMBO/govtool/pull/2525

**Comment by kneerose** [comment]
@MSzalowski, is it deployed on the dev environment? As a dRep , I'm still unable to vote on the new constitution, no confidence, and new committee proposals. Additionally, the dRep voting power is not displayed.

![image](https://github.com/user-attachments/assets/0d58e939-cfa9-4ecd-a4d0-754b964ac7b5)
![image](https://github.com/user-attachments/assets/d9348e8e-5fb7-485d-bf93-07bd945f62e5)
![image](https://github.com/user-attachments/assets/bf3f6ab0-5b8a-478f-8a62-9d78e68afcb9)

CC: @bosko-m
