### ISSUE TITLE
Comments visible but getting the no comments message

### ISSUE THREAD

**Issue by l-br1** [IntersectMBO/govtool#3442]
this is the proposal that was merged https://gov.tools/budget_discussion/299 

<img width="1028" alt="Image" src="https://github.com/user-attachments/assets/3a67821f-33b2-4843-a801-dfd576f5df9a" />

**Comment by bosko-m** [comment]
Seems that there is an issue in comments counting logic. At the time of the report of this issue, there were comments but it showed message **No comments yet**.
After more comments added, count is showing **2**.

potential other duplicates to check:

- https://gov.tools/budget_discussion/237 / https://gov.tools/budget_discussion/240
- https://gov.tools/budget_discussion/269 / https://gov.tools/budget_discussion/273

**Comment by bosko-m** [comment]
Quoting @l-br1 : "there are a few proposals with same titles which are not auto-generated duplicate but manually made (you can identify them because one will be associated with govtooladmin user)"

**Comment by l-br1** [comment]
https://gov.tools/budget_discussion/420 same issue on this

**Comment by bosko-m** [comment]
@l-br1 Already resolved in #3468

**Comment by kneerose** [comment]
**Still reproducible on:** [https://gov.tools/budget_discussion/436](https://gov.tools/budget_discussion/436)

- The comment count is incorrectly shown as **0**, even though there are existing comments.  
- Additionally, the **"No comments"** message is still visible.

This might be related to the duplicate proposal issue: [https://github.com/intersectMBO/govtool/issues/3447](https://github.com/intersectMBO/govtool/issues/3447)

CC: @bosko-m

**Comment by bosko-m** [comment]
This is on dev.
